name: Run Telegram Bot

on:
  workflow_dispatch:
  push:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install python-telegram-bot

      - name: Run bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CARD_NUMBER: ${{ secrets.CARD_NUMBER }}
        run: python bot.py
